name: Updater

on: 
 workflow_dispatch:

jobs:
  Forge-1201:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - run: git config user.email "${{ github.actor }}@users.noreply.github.com"
        if: ${{ github.repository_owner != 'github-actions' }}

      - run: git config user.name "${{ github.actor }}"
        if: ${{ github.repository_owner != 'github-actions' }}   

      - name: Apply Download Link
        run: |
          sed -i "s~devdownloadlink~https://nightly.link/MineOptimiz-Team/MineOptimiz-3rd/workflows/main/1.20.1-Forge-Dev~g" ./config/fancymenu/assets/Update/Update.ps1
          sed -i "s~stabledownloadlink~https://nightly.link/MineOptimiz-Team/MineOptimiz-3rd/workflows/main/1.20.1-Forge-Stable~g" ./config/fancymenu/assets/Update/Update.ps1
      - name: Upload Updater-on-Windows
        uses: actions/upload-artifact@v2
        with:
          name: Update.bat
          path: "./Update.bat"

      - name: Upload Updater-setup
        uses: actions/upload-artifact@v2
        with:
          name: Update-setup.sh
          path: "./Update.sh"

      - name: Upload Update.ps1
        uses: actions/upload-artifact@v2
        with:
          name: Update.ps1
          path: "./config/fancymenu/assets/Update/Update.ps1"

